#!/bin/bash
# Regenerates tests/tectonic_reference.h: values printed by the real Minecraft 26.3 generator (the harness of the
# Tectonic seed-finding project, ../harness/run.sh) for tests/test_tectonic.c.
#
#   tectonic/gen_test_reference.sh > tests/tectonic_reference.h
cd "$(dirname "$0")/.." || exit 1
HARNESS=$(realpath "${HARNESS:-../harness/run.sh}")
export JAVA_OPTS="${JAVA_OPTS:--Xmx3g -XX:+UseParallelGC -XX:ActiveProcessorCount=3}"
IDS="tectonic:terrain_spline/offset/final,router:temperature,router:vegetation,router:continents,router:erosion,router:depth,router:ridges"
TMP=$(mktemp -d); trap 'rm -rf "$TMP"' EXIT
python3 - > "$TMP/points.txt" <<'PY'
import random
r = random.Random(263)
for i in range(48):
    span = [3000, 50000, 1000000, 29999900][i % 4]
    print(r.randint(-span, span), r.randint(-64, 320), r.randint(-span, span))
PY
echo "/* generated by tectonic/gen_test_reference.sh from the real Minecraft 26.3 generator -- do not edit."
echo " * variant, seed, x, y, z, float bits of tectonic:terrain_spline/offset/final, then the climate"
echo " * (temperature, vegetation, continents, erosion, depth, ridges) as float bits. */"
echo "static const struct { int variant; int64_t seed; int x, y, z; uint32_t offset; uint32_t climate[6]; } tectonic_reference[] = {"
vi=0
for v in mod dp; do
  for s in 12345 -7046029254386353131 93929; do
    (cd "$TMP" && "$HARNESS" $v points $s "$IDS" < "$TMP/points.txt" 2>/dev/null) | grep -E '^-?[0-9]+ -?[0-9]+ -?[0-9]+ ' | python3 -c "
import struct, sys
for l in sys.stdin:
    p = l.split()
    bits = ['0x%08x' % struct.unpack('<I', struct.pack('<f', float(v)))[0] for v in p[3:]]
    print('    {%d, %sLL, %s, %s, %s, %s, {%s}},' % ($vi, '$s', p[0], p[1], p[2], bits[0], ', '.join(bits[1:])))
"
  done
  vi=$((vi + 1))
done
echo "};"
